#!/bin/bash
#
#description:
#Mnginx		This is the script for manager nginx start or stop or restart
#
#### BEGIN INFO
# Provides: maycap
# Required-Start: null
# Should-Start: null
# version：1.0
# date:2014-6-11
### END INFO

set -e

PROGDIR=/opt/nginx
PROGNAME=nginx
DAEMON=$PROGDIR/sbin/$PROGNAME
CONFIG=$PROGDIR/conf/nginx.conf
PIDFILE=$PROGDIR/logs/$PROGNAME.pid
DESC="Nginx daemon"

test -x $DAEMON || exit 0

check(){
	echo "Checking $DESC:$PROGNAME"
	$DAEMON -t
}

start(){
	echo -n "Starting $DESC:$PROGNAME"
	$DAEMON
	echo "."
}

stop(){
	echo -n "Stopping $DESC:$PROGNAME"
	ngpid=` pidstat -r -l | grep 'nginx: master process' | grep -v grep | awk '{print $3}'`
	if [[ X"$1" -eq X ]];then
		tag=1
	else
		tag="$1"
	fi
	case $tag in
	1)
		kill -QUIT $ngpid
		;;
	2)
		kill -TERM $ngpid
		;;
	3)
		kill -9 $ngpid
		;;
	*)
		echo "Sorry,Please select 1(从容停止),2(快速停止),3(强制停止)"	
		exit 1
		;;
	esac
	echo "."
}

restart(){
	echo -n "Restarting $DESC:$PROGNAME"
	$DAEMON -s reload
	echo "."
}

case "$1" in
	check)
		check
		;;
	start)
		start
		;;
	stop)
		stop ${2:-1}
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage:$PROGNAME{check|start|stop|restart|reload}" >&2
		exit 1
		;;
esac
exit 0

